# Generated by Django 3.1.1 on 2020-09-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='brands',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='source',
            field=models.IntegerField(blank=True, choices=[(1, 'targi'), (2, 'internet'), (3, 'linkedin'), (4, 'inne')], null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='brands',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='source',
            field=models.IntegerField(blank=True, choices=[(1, 'targi'), (2, 'internet'), (3, 'linkedin'), (4, 'inne')], null=True),
        ),
    ]
