# Generated by Django 3.1.1 on 2020-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0002_auto_20200929_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='linkedin_added',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontak Linkedin'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='whatsapp',
            field=models.IntegerField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='linkedin_added',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontak Linkedin'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='historicalcontactperson',
            name='whatsapp',
            field=models.IntegerField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
