# Generated by Django 3.1.1 on 2020-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0003_auto_20200929_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleslead',
            name='type',
            field=models.IntegerField(choices=[(1, 'Nowy klient'), (2, 'Rozszerzenie oferty')], null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='type',
            field=models.IntegerField(choices=[(1, 'Nowy klient'), (2, 'Rozszerzenie oferty')], null=True),
        ),
    ]
