# Generated by Django 3.1.1 on 2020-09-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0006_delete_historicalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='saleslead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='salesleads.saleslead'),
        ),
    ]
