# Generated by Django 3.1.1 on 2020-10-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0008_auto_20201001_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('activity_type', models.IntegerField(choices=[(1, 'Kontakt telefoniczny'), (2, 'E-mail'), (3, 'Spotkanie')])),
                ('activity_comment', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('activity_done', models.BooleanField(blank=True, null=True, verbose_name='Wykonane')),
                ('saleslead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannedactivities', to='salesleads.saleslead')),
            ],
        ),
    ]
