# Generated by Django 3.1.1 on 2020-10-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0013_auto_20201005_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleslead',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleslead',
            name='longtitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='longtitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
