# Generated by Django 3.1.1 on 2020-10-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0015_auto_20201008_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='latitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='longtitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Szerokość'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='latitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='longtitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Szerokość'),
        ),
    ]
