# Generated by Django 3.1.1 on 2020-10-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0017_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name': 'Kraj', 'verbose_name_plural': 'Kraje'},
        ),
    ]
