# Generated by Django 3.1.1 on 2020-10-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0020_auto_20201014_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='saleslead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='salesleads.saleslead'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='saleslead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='salesleads.saleslead'),
        ),
    ]
