# Generated by Django 3.1.1 on 2020-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0021_auto_20201015_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportuser',
            name='market',
            field=models.IntegerField(blank=True, choices=[(1, 'ME-DE'), (2, 'ME-IT'), (3, 'ME-NL'), (4, 'ME-PE'), (5, 'ME-RU')], null=True, verbose_name='rynek'),
        ),
        migrations.AlterField(
            model_name='historicalplannedactivities',
            name='activity_type',
            field=models.IntegerField(choices=[(1, 'Kontakt telefoniczny'), (2, 'E-mail'), (3, 'Spotkanie')], verbose_name='Forma działania'),
        ),
        migrations.AlterField(
            model_name='plannedactivities',
            name='activity_type',
            field=models.IntegerField(choices=[(1, 'Kontakt telefoniczny'), (2, 'E-mail'), (3, 'Spotkanie')], verbose_name='Forma działania'),
        ),
    ]
