# Generated by Django 3.1.1 on 2020-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesleads', '0022_auto_20201019_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplannedactivities',
            name='activity_done',
            field=models.BooleanField(default=False, null=True, verbose_name='Wykonane'),
        ),
        migrations.AlterField(
            model_name='plannedactivities',
            name='activity_done',
            field=models.BooleanField(default=False, null=True, verbose_name='Wykonane'),
        ),
    ]
